# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('address1', models.CharField(max_length=200)),
                ('address2', models.CharField(max_length=200)),
                ('zipcode', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('single', models.CharField(max_length=200)),
                ('multiple', models.CharField(max_length=200)),
                ('looking', models.CharField(max_length=500)),
                ('hear', models.CharField(max_length=500)),
                ('time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('address1', models.CharField(max_length=200)),
                ('address2', models.CharField(max_length=200)),
                ('zipcode', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('single', models.CharField(max_length=200)),
                ('multiple', models.CharField(max_length=200)),
                ('looking', models.CharField(max_length=500)),
                ('hear', models.CharField(max_length=500)),
                ('requestedwine', models.TextField()),
                ('time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
