# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packaged', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=200)),
                ('variety', models.CharField(max_length=200)),
                ('lot', models.CharField(max_length=200)),
                ('units', models.CharField(max_length=200)),
                ('storage', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=200)),
                ('ava', models.CharField(max_length=200)),
                ('alc', models.CharField(max_length=200)),
                ('chemanalysis', models.CharField(max_length=200)),
                ('current', models.CharField(max_length=500)),
                ('pending', models.CharField(max_length=500)),
                ('other', models.CharField(max_length=500)),
                ('promised', models.CharField(max_length=500)),
                ('available', models.CharField(max_length=500)),
                ('comments', models.CharField(max_length=500)),
            ],
        ),
    ]
