# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='city',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='request',
            name='city',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
